package main

type HumanReadableData struct {
	FlowRate                      float32 `json:"flowRate"`
	EnergyFlowRate                float32 `json:"energyFlowRate"`
	Velocity                      float32 `json:"Velocity"`
	FluidSoundSpeed               float32 `json:"fluidSoundSpeed"`
	PositiveAccumulator           int32   `json:"positiveAccumulator"`
	PositiveDecimalFraction       float32 `json:"positiveDecimalFraction"`
	NegativeAccumulator           int32   `json:"negativeAccumulator"`
	NegativeDecimalFraction       float32 `json:"negativeDecimalFraction"`
	PositiveEnergyAccumulator     int32   `json:"positiveEnergyAccumulator"`
	PositiveEnergyDecimalFraction float32 `json:"positiveEnergyDecimalFraction"`
	NegativeEnergyAccumulator     int32   `json:"negativeEnergyAccumulator"`
	NegativeEnergyDecimalFraction float32 `json:"negativeEnergyDecimalFraction"`
	NetAccumulator                int32   `json:"netAccumulator"`
	NetDecimalFraction            float32 `json:"netDecimalFraction"`
	NetEnergyAccumulator          int32   `json:"netEnergyAccumulator"`
	NetEnergyDecimalFraction      float32 `json:"netEnergyDecimalFraction"`
	Temperature1                  float32 `json:"Temperature1"`
	Temperature2                  float32 `json:"Temperature2"`
	AnalogInputA13                float32 `json:"analogInputA13"`
	AnalogInputA14                float32 `json:"analogInputA14"`
	AnalogInputA15                float32 `json:"analogInputA15"`
	CurrentInputA13               float32 `json:"currentInputA13"`
	CurrentInputA13_2             float32 `json:"currentInputA13_2"`
	CurrentInputA13_3             float32 `json:"currentInputA13_3"`
	SystemPassword                string  `json:"systemPassword"`
	PasswordForHardware           string  `json:"passwordForHardware"`
	Calendar                      string  `json:"calendar"`
	DayHourAutoSave               string  `json:"dayHourAutoSave"`
	KeyToInput                    int16   `json:"keyToInput"`
	GoToWindow                    int16   `json:"goToWindow"`
	LCDLights                     int16   `json:"lCDLights"`
	TimesForBeeper                int16   `json:"timesForBeeper"`
	PulsesLeftForOCT              int16   `json:"pulsesLeftForOCT"`
	ErrorCode                     int8    `json:"errorCode"`
	PT100ResistanceInlet          float32 `json:"pT100ResistanceInlet"`
	PT100ResistanceOutlet         float32 `json:"pT100ResistanceOutlet"`
	TotalTravelTime               float32 `json:"totalTravelTime"`
	DeltaTravelTime               float32 `json:"deltaTravelTime"`
	UpstreamTravelTime            float32 `json:"upstreamTravelTime"`
	DownStreamTravelTime          float32 `json:"downStreamTravelTime"`
	OutputCurrent                 float32 `json:"outputCurrent"`
	WorkingStep                   int8    `json:"workingStep"`
	SignalQuality                 int8    `json:"signalQuality"`
	UpstreamStrength              int16   `json:"upstreamStrength"`
	DownStreamStrength            int16   `json:"downStreamStrength"`
	Language                      int16   `json:"language"`
	RateOfTravelTime              float32 `json:"rateOfTravelTime"`
	ReynoldsNumber                float32 `json:"reynoldsNumber"`
}
