apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataconverter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataconverter-service
  template:
    metadata:
      labels:
        app: dataconverter-service
    spec:
      containers:
      - name: dataconverter-service
        image: "brudnevskij/gambit-dataconverter-service:1.0.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        - containerPort: 5001
        env:
          - name: DATA_API
            value: "http://tuftuf.gambitlabs.fi/feed.txt"

---

apiVersion: v1
kind: Service
metadata:
  name: dataconverter-service
spec:
  selector:
    app: dataconverter-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80
    - protocol: TCP
      name: rpc-port
      port: 5001
      targetPort: 5001